# Generated by Django 3.1.8 on 2021-05-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', models.PositiveIntegerField(help_text='in metres', verbose_name='Border length')),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Currency name (en)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=3, verbose_name='Code ISO 4217'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso_num',
            field=models.CharField(blank=True, max_length=3, verbose_name='Numeric code ISO 4217'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ru_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Currency name (ru)'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subregion', to='flags.region'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, max_length=400, verbose_name='SEO Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='SEO H1')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_index', models.BooleanField(default=True, verbose_name='index')),
                ('is_follow', models.BooleanField(default=True, verbose_name='follow')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('iso_code_a2', models.CharField(max_length=2, unique=True, verbose_name='ISO code (2alpha)')),
                ('iso_code_a3', models.CharField(blank=True, max_length=3, verbose_name='ISO code (3alpha)')),
                ('iso_code_num', models.CharField(blank=True, max_length=4, verbose_name='ISO code (numeric)')),
                ('conventional_long_name', models.CharField(blank=True, max_length=250, verbose_name='Official name')),
                ('local_long_name', models.CharField(blank=True, max_length=250, verbose_name='Official local name')),
                ('local_short_name', models.CharField(blank=True, max_length=250, verbose_name='Short local name')),
                ('ru_capital_name', models.CharField(blank=True, max_length=250, verbose_name='Capital name')),
                ('en_capital_name', models.CharField(blank=True, max_length=250, verbose_name='Столица на английском')),
                ('anthem', models.URLField(blank=True, max_length=250, verbose_name='Anthem URL')),
                ('motto', models.CharField(blank=True, max_length=250, verbose_name='Motto')),
                ('ru_motto', models.CharField(blank=True, max_length=250, verbose_name='Motto Ru translate')),
                ('official_language', models.CharField(blank=True, max_length=50, verbose_name='Official language')),
                ('internet_tld', models.CharField(blank=True, max_length=10, verbose_name='Internet domain')),
                ('phone_code', models.CharField(blank=True, max_length=10, verbose_name='Phone code')),
                ('dl_imgs', models.BooleanField(default=False, verbose_name='Download flag images')),
                ('en_long_form', models.CharField(blank=True, max_length=250, verbose_name='Official long name (en)')),
                ('en_short_form', models.CharField(blank=True, max_length=250, verbose_name='Short name (en)')),
                ('ru_government_type', models.CharField(blank=True, max_length=250, verbose_name='Government type (ru)')),
                ('en_government_type', models.CharField(blank=True, max_length=250, verbose_name='Government type (en)')),
                ('ru_chief_of_state', models.CharField(blank=True, max_length=250, verbose_name='Chief of state (ru)')),
                ('en_chief_of_state', models.CharField(blank=True, max_length=250, verbose_name='Chief of state (en)')),
                ('ru_head_of_government', models.CharField(blank=True, max_length=250, verbose_name='Head of government (ru)')),
                ('en_head_of_government', models.CharField(blank=True, max_length=250, verbose_name='Head of government (en)')),
                ('area_total', models.CharField(blank=True, max_length=250, verbose_name='Total area')),
                ('area_land', models.CharField(blank=True, max_length=250, verbose_name='Land area')),
                ('area_water', models.CharField(blank=True, max_length=250, verbose_name='Water area')),
                ('coastline', models.CharField(blank=True, max_length=250, verbose_name='Coastline')),
                ('area_global_rank', models.PositiveSmallIntegerField(blank=True, verbose_name='Area global rank')),
                ('population_total', models.CharField(blank=True, max_length=250, verbose_name='Population')),
                ('population_date', models.CharField(blank=True, max_length=250, verbose_name='Population stat year')),
                ('population_global_rank', models.PositiveSmallIntegerField(blank=True, verbose_name='Population global rank')),
                ('gdp_value', models.CharField(blank=True, max_length=250, verbose_name='GDP value')),
                ('gdp_date', models.CharField(blank=True, max_length=250, verbose_name='GDP stat year')),
                ('gdp_global_rank', models.PositiveSmallIntegerField(blank=True, verbose_name='GDP global rank')),
                ('external_debt_value', models.CharField(blank=True, max_length=250, verbose_name='External debt value')),
                ('external_debt_date', models.CharField(blank=True, max_length=250, verbose_name='External debt year')),
                ('external_debt_global_rank', models.PositiveSmallIntegerField(blank=True, verbose_name='External debt global rank')),
                ('info_updated', models.CharField(blank=True, max_length=250, verbose_name='Info updated date')),
                ('ru_name_rod', models.CharField(blank=True, max_length=250, verbose_name='Name (rod)')),
                ('ru_name_dat', models.CharField(blank=True, max_length=250, verbose_name='Name (dat)')),
                ('ru_name_vin', models.CharField(blank=True, max_length=250, verbose_name='Name (vin)')),
                ('ru_name_tvo', models.CharField(blank=True, max_length=250, verbose_name='Name (tvo)')),
                ('ru_name_pre', models.CharField(blank=True, max_length=250, verbose_name='Name (pre)')),
                ('border_countries', models.ManyToManyField(blank=True, related_name='_country_border_countries_+', through='flags.BorderCountry', to='flags.Country', verbose_name='Border countries')),
                ('subregion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='flags.subregion')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='bordercountry',
            name='border_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbours', to='flags.country'),
        ),
        migrations.AddField(
            model_name='bordercountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flags.country'),
        ),
        migrations.AlterUniqueTogether(
            name='bordercountry',
            unique_together={('country', 'border_country')},
        ),
    ]
