# Generated by Django 3.1.8 on 2021-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0003_auto_20210527_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='currencies', to='flags.Country', verbose_name='Countries'),
        ),
    ]
