# Generated by Django 3.1.8 on 2021-06-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0004_currency_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercountry',
            name='border',
            field=models.PositiveIntegerField(blank=True, help_text='in metres', null=True, verbose_name='Border length'),
        ),
        migrations.AlterField(
            model_name='bordercountry',
            name='border_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_country', to='flags.country'),
        ),
        migrations.AlterField(
            model_name='bordercountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='flags.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='border_countries',
            field=models.ManyToManyField(related_name='_country_border_countries_+', through='flags.BorderCountry', to='flags.Country', verbose_name='Border countries'),
        ),
    ]
