# Generated by Django 3.1.8 on 2021-06-09 20:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0005_auto_20210606_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, max_length=400, verbose_name='SEO Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='SEO H1')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_index', models.BooleanField(default=True, verbose_name='index')),
                ('is_follow', models.BooleanField(default=True, verbose_name='follow')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_short', models.CharField(max_length=100, verbose_name='Short name')),
                ('description', models.TextField(blank=True, verbose_name='Color description')),
                ('colorgroup_meanings', models.TextField(blank=True, verbose_name='Colorgroup meanings')),
            ],
            options={
                'verbose_name': 'Color group',
                'verbose_name_plural': 'Color groups',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_meaning', models.TextField(blank=True, verbose_name='Color meaning')),
                ('hex', models.CharField(blank=True, max_length=7, unique=True, verbose_name='HEX')),
                ('rgb', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, size=3, verbose_name='RGB')),
                ('cmyk', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, size=4, verbose_name='CMYK')),
                ('hsl', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, size=3, verbose_name='HSL')),
                ('pantone', models.CharField(blank=True, max_length=100, verbose_name='Pantone')),
                ('color_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='flags.colorgroup', verbose_name='Color group')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Flag colors',
            },
        ),
    ]
