# Generated by Django 3.1.8 on 2021-06-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0006_color_colorgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorgroup',
            old_name='name_short',
            new_name='short_name',
        ),
    ]
