# Generated by Django 3.1.8 on 2021-06-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0009_auto_20210629_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagEmoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, max_length=400, verbose_name='SEO Description')),
                ('seo_h1', models.CharField(blank=True, max_length=250, verbose_name='SEO H1')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_index', models.BooleanField(default=True, verbose_name='index')),
                ('is_follow', models.BooleanField(default=True, verbose_name='follow')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('unicode', models.CharField(blank=True, max_length=50, verbose_name='Unicode')),
                ('description', models.TextField(blank=True, verbose_name='Emoji description')),
                ('flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emoji', to='flags.mainflag', verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Flag Emoji',
                'verbose_name_plural': 'Flags Emoji',
            },
        ),
    ]
