# Generated by Django 3.1.8 on 2021-06-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0011_auto_20210629_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagemoji',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji', to='flags.mainflag', verbose_name='Flag'),
        ),
        migrations.CreateModel(
            name='HistoricalFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('from_year', models.PositiveSmallIntegerField(verbose_name='Adopted year')),
                ('to_year', models.PositiveSmallIntegerField(verbose_name='Ended year')),
                ('image_url', models.URLField(max_length=300, verbose_name='SVG image link')),
                ('svg_file', models.FileField(upload_to='historical-flags/', verbose_name='SVG image')),
                ('description', models.TextField(blank=True, verbose_name='Hstorical flag description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_flags', to='flags.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Historical flag',
                'verbose_name_plural': 'Historical flags',
            },
        ),
    ]
