# Generated by Django 3.1.8 on 2021-06-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0012_auto_20210629_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalflag',
            name='svg_file',
            field=models.FileField(blank=True, upload_to='historical-flags/', verbose_name='SVG image'),
        ),
        migrations.CreateModel(
            name='FlagFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Fact caption')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Fact label')),
                ('text', models.TextField(blank=True, verbose_name='Fact text')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Fact image')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='flags.mainflag', verbose_name='Flag')),
            ],
        ),
    ]
