# Generated by Django 3.1.8 on 2021-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0013_auto_20210629_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalflag',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='SVG image link'),
        ),
    ]
