# Generated by Django 3.1.8 on 2021-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0014_auto_20210707_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='dl_imgs',
        ),
        migrations.AddField(
            model_name='mainflag',
            name='dl_imgs',
            field=models.BooleanField(default=False, verbose_name='Download flag images'),
        ),
    ]
