# Generated by Django 3.1.8 on 2021-07-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0017_auto_20210720_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregion',
            name='region',
        ),
        migrations.RemoveField(
            model_name='country',
            name='subregion',
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='flags.newregion'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Subregion',
        ),
    ]
