# Generated by Django 3.1.8 on 2021-07-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0018_auto_20210720_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewRegion',
            new_name='Region',
        ),
    ]
