# Generated by Django 3.1.8 on 2021-07-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0019_auto_20210720_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
