# Generated by Django 3.1.8 on 2021-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0020_auto_20210721_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorgroup',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='country',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='flagelement',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='flagemoji',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='mainflag',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='region',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
    ]
