# Generated by Django 3.1.8 on 2021-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0021_auto_20210721_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='anthem',
            field=models.URLField(blank=True, max_length=500, verbose_name='Anthem URL'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_chief_of_state',
            field=models.CharField(blank=True, max_length=600, verbose_name='Chief of state (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_government_type',
            field=models.CharField(blank=True, max_length=600, verbose_name='Government type (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_head_of_government',
            field=models.CharField(blank=True, max_length=600, verbose_name='Head of government (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_long_form',
            field=models.CharField(blank=True, max_length=500, verbose_name='Official long name (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='motto',
            field=models.CharField(blank=True, max_length=500, verbose_name='Motto'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_chief_of_state',
            field=models.CharField(blank=True, max_length=600, verbose_name='Chief of state (ru)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_government_type',
            field=models.CharField(blank=True, max_length=600, verbose_name='Government type (ru)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_head_of_government',
            field=models.CharField(blank=True, max_length=600, verbose_name='Head of government (ru)'),
        ),
    ]
