# Generated by Django 3.1.8 on 2021-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0022_auto_20210730_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='en_capital_name',
            field=models.CharField(blank=True, max_length=600, verbose_name='Столица на английском'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_capital_name',
            field=models.CharField(blank=True, max_length=600, verbose_name='Capital name'),
        ),
    ]
