# Generated by Django 3.1.8 on 2021-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0023_auto_20210802_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='en_chief_of_state',
            field=models.CharField(blank=True, max_length=700, verbose_name='Chief of state (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_government_type',
            field=models.CharField(blank=True, max_length=700, verbose_name='Government type (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='en_head_of_government',
            field=models.CharField(blank=True, max_length=700, verbose_name='Head of government (en)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_chief_of_state',
            field=models.CharField(blank=True, max_length=700, verbose_name='Chief of state (ru)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_government_type',
            field=models.CharField(blank=True, max_length=700, verbose_name='Government type (ru)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_head_of_government',
            field=models.CharField(blank=True, max_length=700, verbose_name='Head of government (ru)'),
        ),
    ]
