# Generated by Django 3.1.8 on 2021-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0024_auto_20210802_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='internet_tld',
            field=models.CharField(blank=True, max_length=250, verbose_name='Internet domain'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=250, verbose_name='Phone code'),
        ),
    ]
