# Generated by Django 3.1.8 on 2021-08-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0026_auto_20210802_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagemoji',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoji', to='flags.mainflag', verbose_name='Flag'),
        ),
    ]
