# Generated by Django 3.1.8 on 2021-08-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0027_auto_20210802_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordercountry',
            options={'verbose_name': 'Neighbours', 'verbose_name_plural': 'Neighbours'},
        ),
        migrations.RemoveField(
            model_name='mainflag',
            name='flag_day',
        ),
    ]
