# Generated by Django 3.1.8 on 2021-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0028_auto_20210804_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flagfact',
            options={'verbose_name': "Flag's fact", 'verbose_name_plural': "Flag's facts"},
        ),
        migrations.AddField(
            model_name='mainflag',
            name='construction_image_file',
            field=models.FileField(blank=True, upload_to='construction/', verbose_name='Construction SVG image'),
        ),
        migrations.AddField(
            model_name='mainflag',
            name='construction_image_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='Construction SVG image link'),
        ),
    ]
