# Generated by Django 3.1.8 on 2021-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0029_auto_20210805_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainflag',
            name='construction_image',
            field=models.ImageField(blank=True, upload_to='construction/', verbose_name='Construction image'),
        ),
    ]
