# Generated by Django 3.1.8 on 2021-08-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0031_auto_20210816_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='meaning',
            field=models.TextField(blank=True, verbose_name='Color meaning'),
        ),
    ]
