# Generated by Django 3.1.8 on 2021-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0032_color_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(blank=True, max_length=7, verbose_name='HEX'),
        ),
    ]
