# Generated by Django 3.1.8 on 2021-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0033_auto_20210817_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='order',
        ),
        migrations.AddField(
            model_name='color',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='One of main colors'),
        ),
        migrations.AddField(
            model_name='color',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
    ]
