# Generated by Django 3.1.8 on 2021-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0034_auto_20210817_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map_iframe',
            field=models.CharField(blank=True, max_length=600, verbose_name='Map iframe'),
        ),
    ]
