# Generated by Django 3.1.8 on 2021-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0035_country_map_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='map_iframe',
            field=models.TextField(blank=True, verbose_name='Map iframe'),
        ),
    ]
