# Generated by Django 3.1.8 on 2021-08-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0036_auto_20210819_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='map_iframe',
        ),
    ]
