# Generated by Django 3.1.8 on 2021-08-23 07:36

import app.utils.pictures_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0037_remove_country_map_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFlagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.URLField(blank=True, max_length=600, verbose_name='Image URL')),
                ('image', models.FileField(help_text='png, jpg, svg', upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='Image')),
                ('webp', models.FileField(help_text='webp', upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Caption')),
                ('alt', models.CharField(blank=True, max_length=250, verbose_name='Alt text')),
                ('ordering', models.PositiveSmallIntegerField(default=500, verbose_name='Ordering')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flags.historicalflag', verbose_name='Historical flag')),
            ],
            options={
                'verbose_name': 'Historical flag image',
                'verbose_name_plural': 'Historical flag images',
            },
        ),
    ]
