# Generated by Django 3.1.8 on 2021-08-24 12:17

import app.utils.pictures_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0038_historicalflagimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalflag',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='historicalflag',
            name='svg_file',
        ),
        migrations.AlterField(
            model_name='historicalflagimage',
            name='image',
            field=models.FileField(blank=True, help_text='png, jpg, svg', upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='historicalflagimage',
            name='webp',
            field=models.FileField(blank=True, help_text='webp', upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='WebP'),
        ),
    ]
