# Generated by Django 3.1.8 on 2021-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0039_auto_20210824_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainflag',
            name='construction_image_file',
        ),
        migrations.AddField(
            model_name='mainflag',
            name='construction_webp',
            field=models.ImageField(blank=True, upload_to='construction/', verbose_name='WebP'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='construction_image',
            field=models.FileField(blank=True, upload_to='construction/', verbose_name='Construction image'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='construction_image_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='Construction image link'),
        ),
    ]
