# Generated by Django 3.1.8 on 2021-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0040_auto_20210824_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalflag',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='historicalflag',
            name='from_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adopted year'),
        ),
        migrations.AlterField(
            model_name='historicalflag',
            name='to_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ended year'),
        ),
    ]
