# Generated by Django 3.1.8 on 2021-09-01 14:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flags', '0041_auto_20210825_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalflagimage',
            options={'ordering': ('ordering',), 'verbose_name': 'Historical flag image', 'verbose_name_plural': 'Historical flag images'},
        ),
        migrations.AlterField(
            model_name='historicalflag',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Hstorical flag description'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='pictures')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'app.flags'), ('model', 'mainflag')), models.Q(('app_label', 'app.flags'), ('model', 'historicalflag')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
    ]
