# Generated by Django 3.1.8 on 2021-09-01 17:15

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flags', '0042_auto_20210901_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorgroup',
            name='colorgroup_meanings',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Colorgroup meanings'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Color description'),
        ),
        migrations.AlterField(
            model_name='flagelement',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flagfact',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Fact text'),
        ),
        migrations.AlterField(
            model_name='historicalflag',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Hstorical flag description'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='design_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Design description'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='history_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Flag history'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'flags'), ('model', 'mainflag')), models.Q(('app_label', 'flags'), ('model', 'historicalflag')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Region description'),
        ),
        migrations.DeleteModel(
            name='HistoricalFlagImage',
        ),
    ]
