# Generated by Django 3.1.8 on 2021-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0043_auto_20210901_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name/alt'),
        ),
        migrations.AddField(
            model_name='picture',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption/title'),
        ),
    ]
