# Generated by Django 3.1.8 on 2021-09-02 14:00

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0044_auto_20210902_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('ordering',), 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.RemoveField(
            model_name='mainflag',
            name='construction_image_url',
        ),
        migrations.RemoveField(
            model_name='mainflag',
            name='construction_webp',
        ),
        migrations.AddField(
            model_name='mainflag',
            name='construction_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='construction_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='construction'),
        ),
    ]
