# Generated by Django 3.1.8 on 2021-09-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0045_auto_20210902_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalflag',
            options={'ordering': ('ordering',), 'verbose_name': 'Historical flag', 'verbose_name_plural': 'Historical flags'},
        ),
    ]
