# Generated by Django 3.1.8 on 2021-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0046_auto_20210903_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flagfact',
            options={'ordering': ('ordering',), 'verbose_name': "Flag's fact", 'verbose_name_plural': "Flag's facts"},
        ),
        migrations.AddField(
            model_name='flagfact',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Ordering'),
        ),
    ]
