# Generated by Django 3.1.8 on 2021-09-09 21:28

import app.utils.pictures_utils
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flags', '0047_auto_20210903_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='svg',
            field=models.FileField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='SVG image'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='construction_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Construction img URL'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='dl_imgs',
            field=models.BooleanField(default=False, help_text='Downloading images from flagcdn.net', verbose_name='Download flag images'),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='proportion',
            field=models.CharField(blank=True, max_length=10, verbose_name='Proportions'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'flags'), ('model', 'mainflag')), models.Q(('app_label', 'flags'), ('model', 'historicalflag')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model),
        ),
        migrations.AlterField(
            model_name='picture',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
