# Generated by Django 3.1.8 on 2021-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0048_auto_20210910_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainflag',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='flags2', to='flags.Color', verbose_name='Colors'),
        ),
    ]
