# Generated by Django 3.1.8 on 2021-09-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0049_auto_20210910_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainflag',
            name='colors',
        ),
    ]
