# Generated by Django 3.1.8 on 2021-09-29 10:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0051_auto_20210910_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadablePictureFilePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description')),
                ('ordering', models.PositiveSmallIntegerField(default=500, verbose_name='Ordering')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='flags.mainflag', verbose_name='Flag')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='DownloadablePictureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
                ('ordering', models.PositiveSmallIntegerField(default=500, verbose_name='Ordering')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='flags.downloadablepicturefilepreview', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Picture file',
                'verbose_name_plural': 'Picture files',
                'ordering': ('ordering',),
            },
        ),
    ]
