# Generated by Django 3.1.8 on 2021-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0052_downloadablepicturefile_downloadablepicturefilepreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='is_show_on_detail',
            field=models.BooleanField(default=False, verbose_name='Show on detail page'),
        ),
    ]
