# Generated by Django 3.1.8 on 2021-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0053_downloadablepicturefilepreview_is_show_on_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='is_wikimedia',
            field=models.BooleanField(default=False, verbose_name='File from flagcdn'),
        ),
    ]
