# Generated by Django 3.1.8 on 2021-09-30 13:44

import app.utils.pictures_utils
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0054_downloadablepicturefilepreview_is_wikimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFlagPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption/title')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Name/alt')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('svg', models.FileField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='SVG image')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model)),
                ('ordering', models.PositiveSmallIntegerField(default=500, verbose_name='Ordering')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flags.historicalflag')),
            ],
            options={
                'verbose_name': 'Historical picture',
                'verbose_name_plural': 'Historical pictures',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='MainFlagPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption/title')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Name/alt')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('svg', models.FileField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='SVG image')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model)),
                ('flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='flags.mainflag')),
            ],
            options={
                'verbose_name': 'Main picture',
                'verbose_name_plural': 'Main pictures',
            },
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
