# Generated by Django 3.1.8 on 2021-09-30 17:22

import app.utils.pictures_utils
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0055_auto_20210930_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadablepicturefilepreview',
            name='is_wikimedia',
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name/alt'),
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption/title'),
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main picture'),
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='svg',
            field=models.FileField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model, verbose_name='SVG image'),
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='downloadablepicturefilepreview',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=app.utils.pictures_utils.img_path_by_model),
        ),
    ]
