# Generated by Django 3.1.8 on 2021-10-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0056_auto_20210930_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainFlagPicture',
        ),
    ]
