# Generated by Django 3.1.8 on 2021-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0057_delete_mainflagpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorgroup',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flagelement',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainflag',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
