# Generated by Django 3.1.8 on 2021-10-18 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0061_auto_20211018_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='color',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='country',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='currency',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='downloadablepicturefile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadablepicturefile',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='downloadablepicturefile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadablepicturefilepreview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flagfact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagfact',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalflag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalflag',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mainflag',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='color',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='flagelement',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='flagfact',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='historicalflag',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='region',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Ordering'),
        ),
    ]
